using Java.Rmi;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using static Org.Graphstream.Stream.Rmi.ElementType;
using static Org.Graphstream.Stream.Rmi.EventType;
using static Org.Graphstream.Stream.Rmi.AttributeChangeEvent;
using static Org.Graphstream.Stream.Rmi.Mode;
using static Org.Graphstream.Stream.Rmi.What;
using static Org.Graphstream.Stream.Rmi.TimeFormat;
using static Org.Graphstream.Stream.Rmi.OutputType;
using static Org.Graphstream.Stream.Rmi.OutputPolicy;
using static Org.Graphstream.Stream.Rmi.LayoutPolicy;
using static Org.Graphstream.Stream.Rmi.Quality;
using static Org.Graphstream.Stream.Rmi.Option;
using static Org.Graphstream.Stream.Rmi.AttributeType;
using static Org.Graphstream.Stream.Rmi.Balise;
using static Org.Graphstream.Stream.Rmi.GEXFAttribute;
using static Org.Graphstream.Stream.Rmi.METAAttribute;
using static Org.Graphstream.Stream.Rmi.GRAPHAttribute;
using static Org.Graphstream.Stream.Rmi.ATTRIBUTESAttribute;
using static Org.Graphstream.Stream.Rmi.ATTRIBUTEAttribute;
using static Org.Graphstream.Stream.Rmi.NODESAttribute;
using static Org.Graphstream.Stream.Rmi.NODEAttribute;
using static Org.Graphstream.Stream.Rmi.ATTVALUEAttribute;
using static Org.Graphstream.Stream.Rmi.PARENTAttribute;
using static Org.Graphstream.Stream.Rmi.EDGESAttribute;
using static Org.Graphstream.Stream.Rmi.SPELLAttribute;
using static Org.Graphstream.Stream.Rmi.COLORAttribute;
using static Org.Graphstream.Stream.Rmi.POSITIONAttribute;
using static Org.Graphstream.Stream.Rmi.SIZEAttribute;
using static Org.Graphstream.Stream.Rmi.NODESHAPEAttribute;
using static Org.Graphstream.Stream.Rmi.EDGEAttribute;
using static Org.Graphstream.Stream.Rmi.THICKNESSAttribute;
using static Org.Graphstream.Stream.Rmi.EDGESHAPEAttribute;
using static Org.Graphstream.Stream.Rmi.IDType;
using static Org.Graphstream.Stream.Rmi.ModeType;
using static Org.Graphstream.Stream.Rmi.WeightType;
using static Org.Graphstream.Stream.Rmi.EdgeType;
using static Org.Graphstream.Stream.Rmi.NodeShapeType;
using static Org.Graphstream.Stream.Rmi.EdgeShapeType;
using static Org.Graphstream.Stream.Rmi.ClassType;
using static Org.Graphstream.Stream.Rmi.TimeFormatType;
using static Org.Graphstream.Stream.Rmi.GPXAttribute;
using static Org.Graphstream.Stream.Rmi.WPTAttribute;
using static Org.Graphstream.Stream.Rmi.LINKAttribute;
using static Org.Graphstream.Stream.Rmi.EMAILAttribute;
using static Org.Graphstream.Stream.Rmi.PTAttribute;
using static Org.Graphstream.Stream.Rmi.BOUNDSAttribute;
using static Org.Graphstream.Stream.Rmi.COPYRIGHTAttribute;
using static Org.Graphstream.Stream.Rmi.FixType;
using static Org.Graphstream.Stream.Rmi.GraphAttribute;
using static Org.Graphstream.Stream.Rmi.LocatorAttribute;
using static Org.Graphstream.Stream.Rmi.NodeAttribute;
using static Org.Graphstream.Stream.Rmi.EdgeAttribute;
using static Org.Graphstream.Stream.Rmi.DataAttribute;
using static Org.Graphstream.Stream.Rmi.PortAttribute;
using static Org.Graphstream.Stream.Rmi.EndPointAttribute;
using static Org.Graphstream.Stream.Rmi.EndPointType;
using static Org.Graphstream.Stream.Rmi.HyperEdgeAttribute;
using static Org.Graphstream.Stream.Rmi.KeyAttribute;
using static Org.Graphstream.Stream.Rmi.KeyDomain;
using static Org.Graphstream.Stream.Rmi.KeyAttrType;

namespace Gs_Core.Graphstream.Stream.Rmi;

public interface RMIAdapterIn : Remote
{
    void EdgeAttributeAdded(string graphId, long timeId, string edgeId, string attribute, object value);
    void EdgeAttributeChanged(string graphId, long timeId, string edgeId, string attribute, object oldValue, object newValue);
    void EdgeAttributeRemoved(string graphId, long timeId, string edgeId, string attribute);
    void GraphAttributeAdded(string graphId, long timeId, string attribute, object value);
    void GraphAttributeChanged(string graphId, long timeId, string attribute, object oldValue, object newValue);
    void GraphAttributeRemoved(string graphId, long timeId, string attribute);
    void NodeAttributeAdded(string graphId, long timeId, string nodeId, string attribute, object value);
    void NodeAttributeChanged(string graphId, long timeId, string nodeId, string attribute, object oldValue, object newValue);
    void NodeAttributeRemoved(string graphId, long timeId, string nodeId, string attribute);
    void EdgeAdded(string graphId, long timeId, string edgeId, string fromNodeId, string toNodeId, bool directed);
    void EdgeRemoved(string graphId, long timeId, string edgeId);
    void GraphCleared(string graphId, long timeId);
    void NodeAdded(string graphId, long timeId, string nodeId);
    void NodeRemoved(string graphId, long timeId, string nodeId);
    void StepBegins(string graphId, long timeId, double step);
}
