using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using static Org.Graphstream.Stream.Netstream.ElementType;
using static Org.Graphstream.Stream.Netstream.EventType;
using static Org.Graphstream.Stream.Netstream.AttributeChangeEvent;
using static Org.Graphstream.Stream.Netstream.Mode;
using static Org.Graphstream.Stream.Netstream.What;
using static Org.Graphstream.Stream.Netstream.TimeFormat;
using static Org.Graphstream.Stream.Netstream.OutputType;
using static Org.Graphstream.Stream.Netstream.OutputPolicy;
using static Org.Graphstream.Stream.Netstream.LayoutPolicy;
using static Org.Graphstream.Stream.Netstream.Quality;
using static Org.Graphstream.Stream.Netstream.Option;
using static Org.Graphstream.Stream.Netstream.AttributeType;
using static Org.Graphstream.Stream.Netstream.Balise;
using static Org.Graphstream.Stream.Netstream.GEXFAttribute;
using static Org.Graphstream.Stream.Netstream.METAAttribute;
using static Org.Graphstream.Stream.Netstream.GRAPHAttribute;
using static Org.Graphstream.Stream.Netstream.ATTRIBUTESAttribute;
using static Org.Graphstream.Stream.Netstream.ATTRIBUTEAttribute;
using static Org.Graphstream.Stream.Netstream.NODESAttribute;
using static Org.Graphstream.Stream.Netstream.NODEAttribute;
using static Org.Graphstream.Stream.Netstream.ATTVALUEAttribute;
using static Org.Graphstream.Stream.Netstream.PARENTAttribute;
using static Org.Graphstream.Stream.Netstream.EDGESAttribute;
using static Org.Graphstream.Stream.Netstream.SPELLAttribute;
using static Org.Graphstream.Stream.Netstream.COLORAttribute;
using static Org.Graphstream.Stream.Netstream.POSITIONAttribute;
using static Org.Graphstream.Stream.Netstream.SIZEAttribute;
using static Org.Graphstream.Stream.Netstream.NODESHAPEAttribute;
using static Org.Graphstream.Stream.Netstream.EDGEAttribute;
using static Org.Graphstream.Stream.Netstream.THICKNESSAttribute;
using static Org.Graphstream.Stream.Netstream.EDGESHAPEAttribute;
using static Org.Graphstream.Stream.Netstream.IDType;
using static Org.Graphstream.Stream.Netstream.ModeType;
using static Org.Graphstream.Stream.Netstream.WeightType;
using static Org.Graphstream.Stream.Netstream.EdgeType;
using static Org.Graphstream.Stream.Netstream.NodeShapeType;
using static Org.Graphstream.Stream.Netstream.EdgeShapeType;
using static Org.Graphstream.Stream.Netstream.ClassType;
using static Org.Graphstream.Stream.Netstream.TimeFormatType;
using static Org.Graphstream.Stream.Netstream.GPXAttribute;
using static Org.Graphstream.Stream.Netstream.WPTAttribute;
using static Org.Graphstream.Stream.Netstream.LINKAttribute;
using static Org.Graphstream.Stream.Netstream.EMAILAttribute;
using static Org.Graphstream.Stream.Netstream.PTAttribute;
using static Org.Graphstream.Stream.Netstream.BOUNDSAttribute;
using static Org.Graphstream.Stream.Netstream.COPYRIGHTAttribute;
using static Org.Graphstream.Stream.Netstream.FixType;
using static Org.Graphstream.Stream.Netstream.GraphAttribute;
using static Org.Graphstream.Stream.Netstream.LocatorAttribute;
using static Org.Graphstream.Stream.Netstream.NodeAttribute;
using static Org.Graphstream.Stream.Netstream.EdgeAttribute;
using static Org.Graphstream.Stream.Netstream.DataAttribute;
using static Org.Graphstream.Stream.Netstream.PortAttribute;
using static Org.Graphstream.Stream.Netstream.EndPointAttribute;
using static Org.Graphstream.Stream.Netstream.EndPointType;
using static Org.Graphstream.Stream.Netstream.HyperEdgeAttribute;
using static Org.Graphstream.Stream.Netstream.KeyAttribute;
using static Org.Graphstream.Stream.Netstream.KeyDomain;
using static Org.Graphstream.Stream.Netstream.KeyAttrType;

namespace Gs_Core.Graphstream.Stream.Netstream;

public class NetStreamConstants
{
    public static int EVENT_GETVERSION = 0x00;
    public static int EVENT_START = 0x01;
    public static int EVENT_END = 0x02;
    public static int EVENT_ADD_NODE = 0x10;
    public static int EVENT_DEL_NODE = 0x11;
    public static int EVENT_ADD_EDGE = 0x12;
    public static int EVENT_DEL_EDGE = 0x13;
    public static int EVENT_STEP = 0x14;
    public static int EVENT_CLEARED = 0x15;
    public static int EVENT_ADD_GRAPH_ATTR = 0x16;
    public static int EVENT_CHG_GRAPH_ATTR = 0x17;
    public static int EVENT_DEL_GRAPH_ATTR = 0x18;
    public static int EVENT_ADD_NODE_ATTR = 0x19;
    public static int EVENT_CHG_NODE_ATTR = 0x1a;
    public static int EVENT_DEL_NODE_ATTR = 0x1b;
    public static int EVENT_ADD_EDGE_ATTR = 0x1c;
    public static int EVENT_CHG_EDGE_ATTR = 0x1d;
    public static int EVENT_DEL_EDGE_ATTR = 0x1e;
    public static int TYPE_UNKNOWN = 0x00;
    public static int TYPE_BOOLEAN = 0x50;
    public static int TYPE_BOOLEAN_ARRAY = 0x51;
    public static int TYPE_BYTE = 0x52;
    public static int TYPE_BYTE_ARRAY = 0x53;
    public static int TYPE_SHORT = 0x54;
    public static int TYPE_SHORT_ARRAY = 0x55;
    public static int TYPE_INT = 0x56;
    public static int TYPE_INT_ARRAY = 0x57;
    public static int TYPE_LONG = 0x58;
    public static int TYPE_LONG_ARRAY = 0x59;
    public static int TYPE_FLOAT = 0x5a;
    public static int TYPE_FLOAT_ARRAY = 0x5b;
    public static int TYPE_DOUBLE = 0x5c;
    public static int TYPE_DOUBLE_ARRAY = 0x5d;
    public static int TYPE_STRING = 0x5e;
    public static int TYPE_STRING_ARRAY = 0x62;
    public static int TYPE_RAW = 0x5f;
    public static byte TYPE_ARRAY = 0x60;
    public static int TYPE_NULL = 0x61;
    public static int COMMAND = 0x70;
}
