using Java.Util;
using Gs_Core.Graphstream.Ui.GraphicGraph;
using Gs_Core.Graphstream.Ui.View.Util;
using Gs_Core.Graphstream.Ui.Geom;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using static Org.Graphstream.Ui.View.Camera.ElementType;
using static Org.Graphstream.Ui.View.Camera.EventType;
using static Org.Graphstream.Ui.View.Camera.AttributeChangeEvent;
using static Org.Graphstream.Ui.View.Camera.Mode;
using static Org.Graphstream.Ui.View.Camera.What;
using static Org.Graphstream.Ui.View.Camera.TimeFormat;
using static Org.Graphstream.Ui.View.Camera.OutputType;
using static Org.Graphstream.Ui.View.Camera.OutputPolicy;
using static Org.Graphstream.Ui.View.Camera.LayoutPolicy;
using static Org.Graphstream.Ui.View.Camera.Quality;
using static Org.Graphstream.Ui.View.Camera.Option;
using static Org.Graphstream.Ui.View.Camera.AttributeType;
using static Org.Graphstream.Ui.View.Camera.Balise;
using static Org.Graphstream.Ui.View.Camera.GEXFAttribute;
using static Org.Graphstream.Ui.View.Camera.METAAttribute;
using static Org.Graphstream.Ui.View.Camera.GRAPHAttribute;
using static Org.Graphstream.Ui.View.Camera.ATTRIBUTESAttribute;
using static Org.Graphstream.Ui.View.Camera.ATTRIBUTEAttribute;
using static Org.Graphstream.Ui.View.Camera.NODESAttribute;
using static Org.Graphstream.Ui.View.Camera.NODEAttribute;
using static Org.Graphstream.Ui.View.Camera.ATTVALUEAttribute;
using static Org.Graphstream.Ui.View.Camera.PARENTAttribute;
using static Org.Graphstream.Ui.View.Camera.EDGESAttribute;
using static Org.Graphstream.Ui.View.Camera.SPELLAttribute;
using static Org.Graphstream.Ui.View.Camera.COLORAttribute;
using static Org.Graphstream.Ui.View.Camera.POSITIONAttribute;
using static Org.Graphstream.Ui.View.Camera.SIZEAttribute;
using static Org.Graphstream.Ui.View.Camera.NODESHAPEAttribute;
using static Org.Graphstream.Ui.View.Camera.EDGEAttribute;
using static Org.Graphstream.Ui.View.Camera.THICKNESSAttribute;
using static Org.Graphstream.Ui.View.Camera.EDGESHAPEAttribute;
using static Org.Graphstream.Ui.View.Camera.IDType;
using static Org.Graphstream.Ui.View.Camera.ModeType;
using static Org.Graphstream.Ui.View.Camera.WeightType;
using static Org.Graphstream.Ui.View.Camera.EdgeType;
using static Org.Graphstream.Ui.View.Camera.NodeShapeType;
using static Org.Graphstream.Ui.View.Camera.EdgeShapeType;
using static Org.Graphstream.Ui.View.Camera.ClassType;
using static Org.Graphstream.Ui.View.Camera.TimeFormatType;
using static Org.Graphstream.Ui.View.Camera.GPXAttribute;
using static Org.Graphstream.Ui.View.Camera.WPTAttribute;
using static Org.Graphstream.Ui.View.Camera.LINKAttribute;
using static Org.Graphstream.Ui.View.Camera.EMAILAttribute;
using static Org.Graphstream.Ui.View.Camera.PTAttribute;
using static Org.Graphstream.Ui.View.Camera.BOUNDSAttribute;
using static Org.Graphstream.Ui.View.Camera.COPYRIGHTAttribute;
using static Org.Graphstream.Ui.View.Camera.FixType;
using static Org.Graphstream.Ui.View.Camera.GraphAttribute;
using static Org.Graphstream.Ui.View.Camera.LocatorAttribute;
using static Org.Graphstream.Ui.View.Camera.NodeAttribute;
using static Org.Graphstream.Ui.View.Camera.EdgeAttribute;
using static Org.Graphstream.Ui.View.Camera.DataAttribute;
using static Org.Graphstream.Ui.View.Camera.PortAttribute;
using static Org.Graphstream.Ui.View.Camera.EndPointAttribute;
using static Org.Graphstream.Ui.View.Camera.EndPointType;
using static Org.Graphstream.Ui.View.Camera.HyperEdgeAttribute;
using static Org.Graphstream.Ui.View.Camera.KeyAttribute;
using static Org.Graphstream.Ui.View.Camera.KeyDomain;
using static Org.Graphstream.Ui.View.Camera.KeyAttrType;
using static Org.Graphstream.Ui.View.Camera.GraphEvents;
using static Org.Graphstream.Ui.View.Camera.ThreadingModel;
using static Org.Graphstream.Ui.View.Camera.CloseFramePolicy;
using static Org.Graphstream.Ui.View.Camera.Measures;
using static Org.Graphstream.Ui.View.Camera.Token;
using static Org.Graphstream.Ui.View.Camera.Extension;
using static Org.Graphstream.Ui.View.Camera.DefaultEdgeType;
using static Org.Graphstream.Ui.View.Camera.AttrType;
using static Org.Graphstream.Ui.View.Camera.Resolutions;
using static Org.Graphstream.Ui.View.Camera.PropertyType;
using static Org.Graphstream.Ui.View.Camera.Type;
using static Org.Graphstream.Ui.View.Camera.Units;
using static Org.Graphstream.Ui.View.Camera.FillMode;
using static Org.Graphstream.Ui.View.Camera.StrokeMode;
using static Org.Graphstream.Ui.View.Camera.ShadowMode;
using static Org.Graphstream.Ui.View.Camera.VisibilityMode;
using static Org.Graphstream.Ui.View.Camera.TextMode;
using static Org.Graphstream.Ui.View.Camera.TextVisibilityMode;
using static Org.Graphstream.Ui.View.Camera.TextStyle;
using static Org.Graphstream.Ui.View.Camera.IconMode;
using static Org.Graphstream.Ui.View.Camera.SizeMode;
using static Org.Graphstream.Ui.View.Camera.TextAlignment;
using static Org.Graphstream.Ui.View.Camera.TextBackgroundMode;
using static Org.Graphstream.Ui.View.Camera.ShapeKind;
using static Org.Graphstream.Ui.View.Camera.Shape;
using static Org.Graphstream.Ui.View.Camera.SpriteOrientation;
using static Org.Graphstream.Ui.View.Camera.ArrowShape;
using static Org.Graphstream.Ui.View.Camera.JComponents;

namespace Gs_Core.Graphstream.Ui.View.Camera;

public interface Camera
{
    Point3 GetViewCenter();
    void SetViewCenter(double x, double y, double z);
    double GetViewPercent();
    void SetViewPercent(double percent);
    double GetViewRotation();
    void SetViewRotation(double theta);
    double GetGraphDimension();
    void RemoveGraphViewport();
    void SetGraphViewport(double minx, double miny, double maxx, double maxy);
    void ResetView();
    void SetBounds(double minx, double miny, double minz, double maxx, double maxy, double maxz);
    GraphMetrics GetMetrics();
    void SetAutoFitView(bool on);
    Point3 TransformGuToPx(double x, double y, double z);
    Point3 TransformPxToGu(double x, double y);
    bool IsVisible(GraphicElement element);
    GraphicElement FindGraphicElementAt(GraphicGraph graph, EnumSet<InteractiveElement> types, double x, double y);
    Collection<GraphicElement> AllGraphicElementsIn(GraphicGraph graph, EnumSet<InteractiveElement> types, double x1, double y1, double x2, double y2);
}
