using Gs_Core.Graphstream.Ui.GraphicGraph;
using Gs_Core.Graphstream.Ui.View.Camera;
using Gs_Core.Graphstream.Ui.View.Util;
using Java.Util;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using static Org.Graphstream.Ui.View.ElementType;
using static Org.Graphstream.Ui.View.EventType;
using static Org.Graphstream.Ui.View.AttributeChangeEvent;
using static Org.Graphstream.Ui.View.Mode;
using static Org.Graphstream.Ui.View.What;
using static Org.Graphstream.Ui.View.TimeFormat;
using static Org.Graphstream.Ui.View.OutputType;
using static Org.Graphstream.Ui.View.OutputPolicy;
using static Org.Graphstream.Ui.View.LayoutPolicy;
using static Org.Graphstream.Ui.View.Quality;
using static Org.Graphstream.Ui.View.Option;
using static Org.Graphstream.Ui.View.AttributeType;
using static Org.Graphstream.Ui.View.Balise;
using static Org.Graphstream.Ui.View.GEXFAttribute;
using static Org.Graphstream.Ui.View.METAAttribute;
using static Org.Graphstream.Ui.View.GRAPHAttribute;
using static Org.Graphstream.Ui.View.ATTRIBUTESAttribute;
using static Org.Graphstream.Ui.View.ATTRIBUTEAttribute;
using static Org.Graphstream.Ui.View.NODESAttribute;
using static Org.Graphstream.Ui.View.NODEAttribute;
using static Org.Graphstream.Ui.View.ATTVALUEAttribute;
using static Org.Graphstream.Ui.View.PARENTAttribute;
using static Org.Graphstream.Ui.View.EDGESAttribute;
using static Org.Graphstream.Ui.View.SPELLAttribute;
using static Org.Graphstream.Ui.View.COLORAttribute;
using static Org.Graphstream.Ui.View.POSITIONAttribute;
using static Org.Graphstream.Ui.View.SIZEAttribute;
using static Org.Graphstream.Ui.View.NODESHAPEAttribute;
using static Org.Graphstream.Ui.View.EDGEAttribute;
using static Org.Graphstream.Ui.View.THICKNESSAttribute;
using static Org.Graphstream.Ui.View.EDGESHAPEAttribute;
using static Org.Graphstream.Ui.View.IDType;
using static Org.Graphstream.Ui.View.ModeType;
using static Org.Graphstream.Ui.View.WeightType;
using static Org.Graphstream.Ui.View.EdgeType;
using static Org.Graphstream.Ui.View.NodeShapeType;
using static Org.Graphstream.Ui.View.EdgeShapeType;
using static Org.Graphstream.Ui.View.ClassType;
using static Org.Graphstream.Ui.View.TimeFormatType;
using static Org.Graphstream.Ui.View.GPXAttribute;
using static Org.Graphstream.Ui.View.WPTAttribute;
using static Org.Graphstream.Ui.View.LINKAttribute;
using static Org.Graphstream.Ui.View.EMAILAttribute;
using static Org.Graphstream.Ui.View.PTAttribute;
using static Org.Graphstream.Ui.View.BOUNDSAttribute;
using static Org.Graphstream.Ui.View.COPYRIGHTAttribute;
using static Org.Graphstream.Ui.View.FixType;
using static Org.Graphstream.Ui.View.GraphAttribute;
using static Org.Graphstream.Ui.View.LocatorAttribute;
using static Org.Graphstream.Ui.View.NodeAttribute;
using static Org.Graphstream.Ui.View.EdgeAttribute;
using static Org.Graphstream.Ui.View.DataAttribute;
using static Org.Graphstream.Ui.View.PortAttribute;
using static Org.Graphstream.Ui.View.EndPointAttribute;
using static Org.Graphstream.Ui.View.EndPointType;
using static Org.Graphstream.Ui.View.HyperEdgeAttribute;
using static Org.Graphstream.Ui.View.KeyAttribute;
using static Org.Graphstream.Ui.View.KeyDomain;
using static Org.Graphstream.Ui.View.KeyAttrType;
using static Org.Graphstream.Ui.View.GraphEvents;

namespace Gs_Core.Graphstream.Ui.View;

public interface GraphRenderer<S, G>
{
    void Open(GraphicGraph graph, S drawingSurface);
    void Dispose();
    View CreateDefaultView(Viewer viewer, string id);
    Camera GetCamera();
    GraphicElement FindGraphicElementAt(EnumSet<InteractiveElement> types, double x, double y);
    Collection<GraphicElement> AllGraphicElementsIn(EnumSet<InteractiveElement> types, double x1, double y1, double x2, double y2);
    void Render(G g, int x, int y, int width, int height);
    void BeginSelectionAt(double x1, double y1);
    void SelectionGrowsAt(double x, double y);
    void EndSelectionAt(double x2, double y2);
    void MoveElementAtPx(GraphicElement element, double x, double y);
    void Screenshot(string filename, int width, int height);
    void SetBackLayerRenderer(LayerRenderer<G> renderer);
    void SetForeLayoutRenderer(LayerRenderer<G> renderer);
}
