using Java.Io;
using Java.Net;
using Gs_Core.Graphstream.Stream;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using static Org.Graphstream.Stream.Net.ElementType;
using static Org.Graphstream.Stream.Net.EventType;
using static Org.Graphstream.Stream.Net.AttributeChangeEvent;
using static Org.Graphstream.Stream.Net.Mode;
using static Org.Graphstream.Stream.Net.What;
using static Org.Graphstream.Stream.Net.TimeFormat;
using static Org.Graphstream.Stream.Net.OutputType;
using static Org.Graphstream.Stream.Net.OutputPolicy;
using static Org.Graphstream.Stream.Net.LayoutPolicy;
using static Org.Graphstream.Stream.Net.Quality;
using static Org.Graphstream.Stream.Net.Option;
using static Org.Graphstream.Stream.Net.AttributeType;
using static Org.Graphstream.Stream.Net.Balise;
using static Org.Graphstream.Stream.Net.GEXFAttribute;
using static Org.Graphstream.Stream.Net.METAAttribute;
using static Org.Graphstream.Stream.Net.GRAPHAttribute;
using static Org.Graphstream.Stream.Net.ATTRIBUTESAttribute;
using static Org.Graphstream.Stream.Net.ATTRIBUTEAttribute;
using static Org.Graphstream.Stream.Net.NODESAttribute;
using static Org.Graphstream.Stream.Net.NODEAttribute;
using static Org.Graphstream.Stream.Net.ATTVALUEAttribute;
using static Org.Graphstream.Stream.Net.PARENTAttribute;
using static Org.Graphstream.Stream.Net.EDGESAttribute;
using static Org.Graphstream.Stream.Net.SPELLAttribute;
using static Org.Graphstream.Stream.Net.COLORAttribute;
using static Org.Graphstream.Stream.Net.POSITIONAttribute;
using static Org.Graphstream.Stream.Net.SIZEAttribute;
using static Org.Graphstream.Stream.Net.NODESHAPEAttribute;
using static Org.Graphstream.Stream.Net.EDGEAttribute;
using static Org.Graphstream.Stream.Net.THICKNESSAttribute;
using static Org.Graphstream.Stream.Net.EDGESHAPEAttribute;
using static Org.Graphstream.Stream.Net.IDType;
using static Org.Graphstream.Stream.Net.ModeType;
using static Org.Graphstream.Stream.Net.WeightType;
using static Org.Graphstream.Stream.Net.EdgeType;
using static Org.Graphstream.Stream.Net.NodeShapeType;
using static Org.Graphstream.Stream.Net.EdgeShapeType;
using static Org.Graphstream.Stream.Net.ClassType;
using static Org.Graphstream.Stream.Net.TimeFormatType;
using static Org.Graphstream.Stream.Net.GPXAttribute;
using static Org.Graphstream.Stream.Net.WPTAttribute;
using static Org.Graphstream.Stream.Net.LINKAttribute;
using static Org.Graphstream.Stream.Net.EMAILAttribute;
using static Org.Graphstream.Stream.Net.PTAttribute;
using static Org.Graphstream.Stream.Net.BOUNDSAttribute;
using static Org.Graphstream.Stream.Net.COPYRIGHTAttribute;
using static Org.Graphstream.Stream.Net.FixType;
using static Org.Graphstream.Stream.Net.GraphAttribute;
using static Org.Graphstream.Stream.Net.LocatorAttribute;
using static Org.Graphstream.Stream.Net.NodeAttribute;
using static Org.Graphstream.Stream.Net.EdgeAttribute;
using static Org.Graphstream.Stream.Net.DataAttribute;
using static Org.Graphstream.Stream.Net.PortAttribute;
using static Org.Graphstream.Stream.Net.EndPointAttribute;
using static Org.Graphstream.Stream.Net.EndPointType;
using static Org.Graphstream.Stream.Net.HyperEdgeAttribute;
using static Org.Graphstream.Stream.Net.KeyAttribute;
using static Org.Graphstream.Stream.Net.KeyDomain;
using static Org.Graphstream.Stream.Net.KeyAttrType;

namespace Gs_Core.Graphstream.Stream.Net;

public interface URLSource : Source
{
    void FetchAll(URL url);
    void Begin(URL url);
    bool NextEvents();
    void End();
}
