using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using static Org.Graphstream.Ui.View.Util.ElementType;
using static Org.Graphstream.Ui.View.Util.EventType;
using static Org.Graphstream.Ui.View.Util.AttributeChangeEvent;
using static Org.Graphstream.Ui.View.Util.Mode;
using static Org.Graphstream.Ui.View.Util.What;
using static Org.Graphstream.Ui.View.Util.TimeFormat;
using static Org.Graphstream.Ui.View.Util.OutputType;
using static Org.Graphstream.Ui.View.Util.OutputPolicy;
using static Org.Graphstream.Ui.View.Util.LayoutPolicy;
using static Org.Graphstream.Ui.View.Util.Quality;
using static Org.Graphstream.Ui.View.Util.Option;
using static Org.Graphstream.Ui.View.Util.AttributeType;
using static Org.Graphstream.Ui.View.Util.Balise;
using static Org.Graphstream.Ui.View.Util.GEXFAttribute;
using static Org.Graphstream.Ui.View.Util.METAAttribute;
using static Org.Graphstream.Ui.View.Util.GRAPHAttribute;
using static Org.Graphstream.Ui.View.Util.ATTRIBUTESAttribute;
using static Org.Graphstream.Ui.View.Util.ATTRIBUTEAttribute;
using static Org.Graphstream.Ui.View.Util.NODESAttribute;
using static Org.Graphstream.Ui.View.Util.NODEAttribute;
using static Org.Graphstream.Ui.View.Util.ATTVALUEAttribute;
using static Org.Graphstream.Ui.View.Util.PARENTAttribute;
using static Org.Graphstream.Ui.View.Util.EDGESAttribute;
using static Org.Graphstream.Ui.View.Util.SPELLAttribute;
using static Org.Graphstream.Ui.View.Util.COLORAttribute;
using static Org.Graphstream.Ui.View.Util.POSITIONAttribute;
using static Org.Graphstream.Ui.View.Util.SIZEAttribute;
using static Org.Graphstream.Ui.View.Util.NODESHAPEAttribute;
using static Org.Graphstream.Ui.View.Util.EDGEAttribute;
using static Org.Graphstream.Ui.View.Util.THICKNESSAttribute;
using static Org.Graphstream.Ui.View.Util.EDGESHAPEAttribute;
using static Org.Graphstream.Ui.View.Util.IDType;
using static Org.Graphstream.Ui.View.Util.ModeType;
using static Org.Graphstream.Ui.View.Util.WeightType;
using static Org.Graphstream.Ui.View.Util.EdgeType;
using static Org.Graphstream.Ui.View.Util.NodeShapeType;
using static Org.Graphstream.Ui.View.Util.EdgeShapeType;
using static Org.Graphstream.Ui.View.Util.ClassType;
using static Org.Graphstream.Ui.View.Util.TimeFormatType;
using static Org.Graphstream.Ui.View.Util.GPXAttribute;
using static Org.Graphstream.Ui.View.Util.WPTAttribute;
using static Org.Graphstream.Ui.View.Util.LINKAttribute;
using static Org.Graphstream.Ui.View.Util.EMAILAttribute;
using static Org.Graphstream.Ui.View.Util.PTAttribute;
using static Org.Graphstream.Ui.View.Util.BOUNDSAttribute;
using static Org.Graphstream.Ui.View.Util.COPYRIGHTAttribute;
using static Org.Graphstream.Ui.View.Util.FixType;
using static Org.Graphstream.Ui.View.Util.GraphAttribute;
using static Org.Graphstream.Ui.View.Util.LocatorAttribute;
using static Org.Graphstream.Ui.View.Util.NodeAttribute;
using static Org.Graphstream.Ui.View.Util.EdgeAttribute;
using static Org.Graphstream.Ui.View.Util.DataAttribute;
using static Org.Graphstream.Ui.View.Util.PortAttribute;
using static Org.Graphstream.Ui.View.Util.EndPointAttribute;
using static Org.Graphstream.Ui.View.Util.EndPointType;
using static Org.Graphstream.Ui.View.Util.HyperEdgeAttribute;
using static Org.Graphstream.Ui.View.Util.KeyAttribute;
using static Org.Graphstream.Ui.View.Util.KeyDomain;
using static Org.Graphstream.Ui.View.Util.KeyAttrType;
using static Org.Graphstream.Ui.View.Util.GraphEvents;
using static Org.Graphstream.Ui.View.Util.ThreadingModel;
using static Org.Graphstream.Ui.View.Util.CloseFramePolicy;
using static Org.Graphstream.Ui.View.Util.Measures;
using static Org.Graphstream.Ui.View.Util.Token;
using static Org.Graphstream.Ui.View.Util.Extension;
using static Org.Graphstream.Ui.View.Util.DefaultEdgeType;
using static Org.Graphstream.Ui.View.Util.AttrType;
using static Org.Graphstream.Ui.View.Util.Resolutions;
using static Org.Graphstream.Ui.View.Util.PropertyType;
using static Org.Graphstream.Ui.View.Util.Type;
using static Org.Graphstream.Ui.View.Util.Units;
using static Org.Graphstream.Ui.View.Util.FillMode;
using static Org.Graphstream.Ui.View.Util.StrokeMode;
using static Org.Graphstream.Ui.View.Util.ShadowMode;
using static Org.Graphstream.Ui.View.Util.VisibilityMode;
using static Org.Graphstream.Ui.View.Util.TextMode;
using static Org.Graphstream.Ui.View.Util.TextVisibilityMode;
using static Org.Graphstream.Ui.View.Util.TextStyle;
using static Org.Graphstream.Ui.View.Util.IconMode;
using static Org.Graphstream.Ui.View.Util.SizeMode;
using static Org.Graphstream.Ui.View.Util.TextAlignment;
using static Org.Graphstream.Ui.View.Util.TextBackgroundMode;
using static Org.Graphstream.Ui.View.Util.ShapeKind;
using static Org.Graphstream.Ui.View.Util.Shape;
using static Org.Graphstream.Ui.View.Util.SpriteOrientation;
using static Org.Graphstream.Ui.View.Util.ArrowShape;
using static Org.Graphstream.Ui.View.Util.JComponents;
using static Org.Graphstream.Ui.View.Util.InteractiveElement;

namespace Gs_Core.Graphstream.Ui.View.Util;

public enum InteractiveElement
{
    NODE,
    EDGE,
    SPRITE
}
